// mrs_generate: turns operator geometry (GeoJSON) into a timeline of tasks (spec 11 §4.3).
// Usage: mrs_generate <features.geojson> <mission header .mrs> [--at SECONDS] [--land r1,r2,...]
//                     [--issuer op] [--first N]
// Each feature's "task" property picks the generator (spec 11 §4.2). The timeline goes to
// standard output; every task is dispatched at --at (default 1 s).
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "mrs/generators/Generators.h"
#include "mrs/protocol/Parser.h"

using namespace MRS;

namespace {
	std::string ReadFile(const std::string& path) {
		std::ifstream in(path, std::ios::binary);
		if (!in) throw std::runtime_error("cannot open " + path);
		std::stringstream s;
		s << in.rdbuf();
		return s.str();
	}

	double NumOf(const Protocol::Field& f) { return f.type == Protocol::FieldType::Int ? static_cast<double>(f.i) : f.n; }
}

int main(int argc, char** argv) {
	if (argc < 3) {
		std::cerr << "usage: mrs_generate <features.geojson> <mission header .mrs> [--at SECONDS] [--land r1,r2,...] [--issuer op] [--first N]\n";
		return 2;
	}
	try {
		Generators::GeoJsonOptions o;
		double at = 1.0;
		for (int k = 3; k < argc; ++k) {
			const std::string a = argv[k];
			if (k + 1 >= argc) throw std::runtime_error("missing value after " + a);
			const std::string v = argv[++k];
			if (a == "--at") at = std::stod(v);
			else if (a == "--issuer") o.issuer = v;
			else if (a == "--first") o.first_id = std::stoi(v);
			else if (a == "--land") {
				std::stringstream s(v);
				std::string r;
				while (std::getline(s, r, ',')) o.land_robots.push_back(r);
			} else throw std::runtime_error("unknown option " + a);
		}
		auto header = Protocol::Parse(ReadFile(argv[2]));
		if (!header.Ok()) throw std::runtime_error(std::string("mission header: ") + header.error->message);
		const Protocol::Record* h = nullptr;
		for (const auto& r : header.document.records)
			if (r.code == "H_M") h = &r;
		if (!h) throw std::runtime_error(std::string("no H_M record in ") + argv[2]);
		const Environment::GeoReference geo(NumOf(h->fields.at(1)), NumOf(h->fields.at(2)), NumOf(h->fields.at(3)));
		const auto features = Generators::ReadGeoJson(ReadFile(argv[1]), geo);
		std::vector<std::pair<double, Protocol::Record>> entries;
		for (auto& t : Generators::TasksFromGeoJson(features, o)) entries.push_back({at, std::move(t)});
		std::cout << Generators::Timeline(entries, std::string("Generated by mrs_generate from ") + argv[1] + " (spec 11 §4).");
	} catch (const std::exception& e) {
		std::cerr << e.what() << "\n";
		return 1;
	}
	return 0;
}
